### PR TITLE
EuropaPark implementation improved

### PR DESCRIPTION
**Pull request by jeanmatthieud**
Updating EuropaPark request and response
and fix for node v0.8

### CODE REVIEW

**Comment by cubehouse** [comment]
Nice stuff! Looks great, will merge in and publish a new version shortly.

**Comment by jeanmatthieud** [comment]
Thanks, I will use it soon

**Comment by jeanmatthieud** [comment]
The last build failed because of this merge. I fon't understand as the build pass this morning on my dev station (and the park is still closed).
Maybe you should enable the response logger to further analysis on

**Comment by cubehouse** [comment]
EuropaPark seems super inconsistent with it's returned data.

When we move to 4.0.0, with a code overhaul/refactor, I'm intending to have offline unit tests using cached network requests, so the unit tests can run regardless of the live server status. Then we can have an environment variable or something to turn on online unit tests to check APIs still work. I think this will stop merges failing just because a server somewhere is returning 500 status codes, and help us tell the difference between broken code and network glitches.

Tests seem to be running successfully at the moment though, for now!

**Comment by jeanmatthieud** [comment]
Yes, I've seen some strange behavior.
I'm trying to add Sentry to my backoffice (which use WDWJS) to report such behavior.
I will let you know if I discover something.

**Pull request merged**
