### PR TITLE
Add special time for Tokyo Disney

### PR DESCRIPTION
**Pull request by tericky**
At OpeningTime Object, add two type of special time for Tokyo Disney: **Character Greeting** and **Parades and Shows**.

### CODE REVIEW

**Comment by cubehouse** [comment]
Ignore the failed check.
Will look at this sometime in the next few days :)
Glancing at it though, could we use the "supports_ride_schedules" style properties on parks for this, so we can programatically determine which parks support such features.

**Comment by tericky** [comment]
But both of them are not showing at ride list, because they are in the event group not in attraction, so that if put them into ride schedules, they can't match the ride list in the code process now.

Or, redesign the structure of rides info?

**Comment by cubehouse** [comment]
I'm not entirely sure what this commit does, can you explain what this adds to the dataset, update the README with any new variables that are available, and if this is something that needs to be extended to other parts of the API?

**Comment by tericky** [comment]
This commit implement the "special" property of API GetOpeningTimes, Tokyo Disney lost this data, so I put the Greeting and Show schedule into here.

**Comment by cubehouse** [comment]
I've checked this out and ran it, I don't think this fits into what "special schedules" means for other parks. This is being used to represent extended opening times for Extra Magic Hours and such.

At the moment, the API does not support returning greets/shows/parades for any parks. See issue #9 for a request to add entertainment to the API. If you want to add this, please extend parkBase with a new method for returning entertainment and implement it for the Tokyo parks.

**Comment by cubehouse** [comment]
I'm afraid I'm closing this pull request as it's not had any activity for a while.

If you wish to have entertainment times, we need to implement park entertainment as a separate feature to the project, as schedules for parades etc. doesn't belong in the park's opening times.

Please continue any work in #9 if we want this in the project.

Thanks

**Pull request closed without merging**
